In [1]:
import sys
sys.path.append('../')

import numpy as np
import pandas as pd 

from scripts.analytics import *
from scripts.algorithms import *

In [2]:
name = "studentportuguese"
namex = "Student-portuguese "

d = 30

###knn
graphs = np.load("../graphs/"+name+"_knn_random.npy", allow_pickle=True)
###threshold
graphsz = np.load("../graphs/"+name+"_thresh_random.npy", allow_pickle=True)

# Compute bruteforce algorithm results

## Nearest neighbor

In [3]:
### read the random, greedy results
df_greedy1 = pd.read_csv("./sm_results/"+name+"_knn_summary.csv")
df_greedy1.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,kmax,n,m,dataset,graphid
0,1,109.0,set(),109.0,{38},109.0,set(),109.0,{44},109.0,...,1.0,1.0,1.0,0.027287,0.000708,1,224,46,studentportuguese (30),0
1,2,109.0,set(),109.0,"{4, 38}",109.0,set(),109.0,"{44, 7}",109.0,...,1.0,1.0,1.0,0.023619,0.000450,1,224,46,studentportuguese (30),0
2,3,109.0,set(),109.0,"{1, 4, 38}",109.0,set(),109.0,"{1, 44, 7}",109.0,...,1.0,1.0,1.0,0.031862,0.000650,1,224,46,studentportuguese (30),0
3,4,109.0,set(),109.0,"{46, 1, 4, 38}",109.0,set(),109.0,"{1, 18, 44, 7}",109.0,...,1.0,1.0,1.0,0.034420,0.000778,1,224,46,studentportuguese (30),0
4,5,109.0,set(),109.0,"{1, 4, 38, 11, 46}",109.0,set(),109.0,"{1, 7, 44, 16, 18}",109.0,...,1.0,1.0,1.0,0.024233,0.000594,1,224,46,studentportuguese (30),0

In [4]:
greedy_bruteforce_algosdf = pd.DataFrame()
all_bruteforce = pd.DataFrame()

for lx in range(len(graphs)):

    r_edges_random  = graphs[lx]["edges"]
    r_labels_random = graphs[lx]["labels"]
    
    optls = budget_opts(edges=r_edges_random, labels=r_labels_random, budget=5)
    df_optls = pd.DataFrame(optls)
    df_optls["graphidx"] = [lx]*len(df_optls)
    all_bruteforce = pd.concat([all_bruteforce, df_optls], ignore_index=True)


    df_greedy11 = df_greedy1[df_greedy1["graphid"]==lx][['K', 'Sg', 'F(Sg)', 'Sr', 'F(Sr)', '(Sg+ U Sg-)*',
                                                         'F(Sg+ U Sg-)*', '(Sr+ U Sr-)*', 'F(Sr+ U Sr-)*', 'kmax']]

    merged = pd.merge(df_greedy11, df_optls, left_on="K", right_on="b", how="inner").drop(columns=["b"])
    merged["F(Sg)/F(S*)"] = merged["F(Sg)"] / merged["F(S*)"]
    merged["F(Sr)/F(S*)"] = merged["F(Sr)"] / merged["F(S*)"]
    merged["F(Sg+ U Sg-)* / F(S*)"] = merged["F(Sg+ U Sg-)*"] / merged["F(S*)"]
    merged["F(Sr+ U Sr-)* / F(S*)"] = merged["F(Sr+ U Sr-)*"] / merged["F(S*)"]

    summary_dfv = merged[[
        "K", "Sg", "F(Sg)", "Sr", "F(Sr)", "(Sg+ U Sg-)*", "F(Sg+ U Sg-)*",
        "(Sr+ U Sr-)*", "F(Sr+ U Sr-)*", "F(S*)", "S*",
        "F(Sg)/F(S*)", "F(Sr)/F(S*)", "F(Sg+ U Sg-)* / F(S*)", "F(Sr+ U Sr-)* / F(S*)",
        "BFtime", "kmax"
    ]]

    summary_df = summary_dfv.copy()
    summary_df["n"] = [graphs[lx]['n']]*len(summary_df)
    summary_df["m"] = [graphs[lx]['m']]*len(summary_df)
    summary_df["dataset"] = [name+" ("+ str(d) + ")"]*len(summary_df)
    summary_df["graphid"] = [lx]*len(summary_df)

    
    greedy_bruteforce_algosdf = pd.concat([greedy_bruteforce_algosdf, summary_df], ignore_index=True)

## Thresholding

In [5]:
df_greedy1z = pd.read_csv("./sm_results/"+name+"_thresh_summary.csv")
df_greedy1z.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,r,n,m,dataset,graphid
0,1,5.0,{32},5.0,{32},5.0,{32},5.0,{28},5.0,...,1.0,1.0,1.0,0.002330,0.000321,4.0,224,6,studentportuguese (30),0
1,2,5.0,{32},5.0,{32},5.0,{32},5.0,"{32, 28}",5.0,...,1.0,1.0,1.0,0.007512,0.000632,4.0,224,6,studentportuguese (30),0
2,3,5.0,{32},5.0,{32},5.0,{32},5.0,"{32, 41, 28}",5.0,...,1.0,1.0,1.0,0.005219,0.000641,4.0,224,6,studentportuguese (30),0
3,4,5.0,{32},5.0,{32},5.0,{32},5.0,"{32, 41, 18, 28}",5.0,...,1.0,1.0,1.0,0.007218,0.000636,4.0,224,6,studentportuguese (30),0
4,5,5.0,{32},5.0,{32},5.0,{32},5.0,"{32, 41, 16, 18, 28}",5.0,...,1.0,1.0,1.0,0.006605,0.000649,4.0,224,6,studentportuguese (30),0

In [6]:
greedy_bruteforce_algosdfz = pd.DataFrame()
all_bruteforcez = pd.DataFrame()

for lz in range(len(graphsz)):

    r_edges_randomz  = graphsz[lz]["edges"]
    r_labels_randomz = graphsz[lz]["labels"]
    
    optlsz = budget_opts(edges=r_edges_randomz, labels=r_labels_randomz, budget=5)
    
    df_optlsz = pd.DataFrame(optlsz)
    df_optlsz["graphidx"] = [lz]*len(df_optlsz)
    all_bruteforcez = pd.concat([all_bruteforcez, df_optlsz], ignore_index=True)


    df_greedy11z = df_greedy1z[df_greedy1z["graphid"]==lz][['K', 'Sg', 'F(Sg)', 'Sr', 'F(Sr)', '(Sg+ U Sg-)*',
                                                         'F(Sg+ U Sg-)*', '(Sr+ U Sr-)*', 'F(Sr+ U Sr-)*', 'r']]

    mergedz = pd.merge(df_greedy11z, df_optlsz, left_on="K", right_on="b", how="inner").drop(columns=["b"])
    mergedz["F(Sg)/F(S*)"] = mergedz["F(Sg)"] / mergedz["F(S*)"]
    mergedz["F(Sr)/F(S*)"] = mergedz["F(Sr)"] / mergedz["F(S*)"]
    mergedz["F(Sg+ U Sg-)* / F(S*)"] = mergedz["F(Sg+ U Sg-)*"] / mergedz["F(S*)"]
    mergedz["F(Sr+ U Sr-)* / F(S*)"] = mergedz["F(Sr+ U Sr-)*"] / mergedz["F(S*)"]

    summary_dfzv = mergedz[[
        "K", "Sg", "F(Sg)", "Sr", "F(Sr)", "(Sg+ U Sg-)*", "F(Sg+ U Sg-)*",
        "(Sr+ U Sr-)*", "F(Sr+ U Sr-)*", "F(S*)", "S*",
        "F(Sg)/F(S*)", "F(Sr)/F(S*)", "F(Sg+ U Sg-)* / F(S*)", "F(Sr+ U Sr-)* / F(S*)",
        "BFtime", "r"
    ]]

    summary_dfz = summary_dfzv.copy()
    summary_dfz["n"] = [graphsz[lz]['n']]*len(summary_dfz)
    summary_dfz["m"] = [graphsz[lz]['m']]*len(summary_dfz)
    summary_dfz["dataset"] = [name+" ("+ str(d) + ")"]*len(summary_dfz)
    summary_dfz["graphid"] = [lz]*len(summary_dfz)

    
    greedy_bruteforce_algosdfz = pd.concat([greedy_bruteforce_algosdfz, summary_dfz], ignore_index=True)

# Save Results

In [7]:
greedy_bruteforce_algosdf.head()

,K,Sg,F(Sg),Sr,F(Sr),(Sg+ U Sg-)*,F(Sg+ U Sg-)*,(Sr+ U Sr-)*,F(Sr+ U Sr-)*,F(S*),...,F(Sg)/F(S*),F(Sr)/F(S*),F(Sg+ U Sg-)* / F(S*),F(Sr+ U Sr-)* / F(S*),BFtime,kmax,n,m,dataset,graphid
0,1,set(),109.0,{44},109.0,set(),109.0,{38},109.0,109.0,...,1.0,1.0,1.0,1.0,0.027742,1,224,46,studentportuguese (30),0
1,2,set(),109.0,"{44, 7}",109.0,set(),109.0,"{4, 38}",109.0,109.0,...,1.0,1.0,1.0,1.0,0.512651,1,224,46,studentportuguese (30),0
2,3,set(),109.0,"{1, 44, 7}",109.0,set(),109.0,"{1, 4, 38}",109.0,109.0,...,1.0,1.0,1.0,1.0,7.363063,1,224,46,studentportuguese (30),0
3,4,set(),109.0,"{1, 18, 44, 7}",109.0,set(),109.0,"{46, 1, 4, 38}",109.0,109.0,...,1.0,1.0,1.0,1.0,76.405259,1,224,46,studentportuguese (30),0
4,5,set(),109.0,"{1, 7, 44, 16, 18}",109.0,set(),109.0,"{1, 4, 38, 11, 46}",109.0,109.0,...,1.0,1.0,1.0,1.0,609.473376,1,224,46,studentportuguese (30),0

In [8]:
all_bruteforce.head()

   b  F(S*)  S*     BFtime  graphidx
0  0  109.0  {}   0.001527         0
1  1  109.0  {}   0.027742         0
2  2  109.0  {}   0.512651         0
3  3  109.0  {}   7.363063         0
4  4  109.0  {}  76.405259         0

In [9]:
greedy_bruteforce_algosdfz.head()

,K,Sg,F(Sg),Sr,F(Sr),(Sg+ U Sg-)*,F(Sg+ U Sg-)*,(Sr+ U Sr-)*,F(Sr+ U Sr-)*,F(S*),...,F(Sg)/F(S*),F(Sr)/F(S*),F(Sg+ U Sg-)* / F(S*),F(Sr+ U Sr-)* / F(S*),BFtime,r,n,m,dataset,graphid
0,1,{32},5.0,{28},5.0,{32},5.0,{32},5.0,5.0,...,1.0,1.0,1.0,1.0,0.002555,4.0,224,6,studentportuguese (30),0
1,2,{32},5.0,"{32, 28}",5.0,{32},5.0,{32},5.0,5.0,...,1.0,1.0,1.0,1.0,0.008099,4.0,224,6,studentportuguese (30),0
2,3,{32},5.0,"{32, 41, 28}",5.0,{32},5.0,{32},5.0,5.0,...,1.0,1.0,1.0,1.0,0.013763,4.0,224,6,studentportuguese (30),0
3,4,{32},5.0,"{32, 41, 18, 28}",5.0,{32},5.0,{32},5.0,5.0,...,1.0,1.0,1.0,1.0,0.017548,4.0,224,6,studentportuguese (30),0
4,5,{32},5.0,"{32, 41, 16, 18, 28}",5.0,{32},5.0,{32},5.0,5.0,...,1.0,1.0,1.0,1.0,0.019163,4.0,224,6,studentportuguese (30),0

In [10]:
all_bruteforcez.head()

   b     F(S*)    S*    BFtime  graphidx
0  0  4.666667    {}  0.001939         0
1  1  5.000000  {32}  0.002555         0
2  2  5.000000  {32}  0.008099         0
3  3  5.000000  {32}  0.013763         0
4  4  5.000000  {32}  0.017548         0

In [11]:
greedy_bruteforce_algosdf.to_csv("./sm_results/"+name+"_knn_greedy_rdm_bruteforce.csv", index=False)
all_bruteforce.to_csv("./sm_results/"+name+"_knn_allbruteforce.csv", index=False)

greedy_bruteforce_algosdfz.to_csv("./sm_results/"+name+"_thresh_greedy_rdm_bruteforce.csv", index=False)
all_bruteforcez.to_csv("./sm_results/"+name+"_thresh_allbruteforce.csv", index=False)