In [1]:
import sys
sys.path.append('../')

import numpy as np
import pandas as pd 

from scripts.analytics import *
from scripts.algorithms import *

In [2]:
name = "studentmath"
namex = "Student-mat "
d = 30


###knn
graphs = np.load("../graphs/"+name+"_knn_random.npy", allow_pickle=True)
###threshold
graphsz = np.load("../graphs/"+name+"_thresh_random.npy", allow_pickle=True)

# Compute bruteforce algorithm results

## Nearest neighbor

In [3]:
### read the random, greedy results
df_greedy1 = pd.read_csv("./sm_results/"+name+"_knn_summary.csv")
df_greedy1.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,kmax,n,m,dataset,graphid
0,1,106.0,set(),106.0,{8},106.0,set(),106.0,{7},106.0,...,1.0,1.0,1.0,0.014505,0.000386,1,206,35,studentmath (30),0
1,2,106.0,set(),106.0,"{8, 3}",106.0,set(),106.0,"{1, 7}",106.0,...,1.0,1.0,1.0,0.014144,0.000740,1,206,35,studentmath (30),0
2,3,106.0,set(),106.0,"{8, 3, 15}",106.0,set(),106.0,"{1, 19, 7}",106.0,...,1.0,1.0,1.0,0.012386,0.000501,1,206,35,studentmath (30),0
3,4,106.0,set(),106.0,"{8, 3, 14, 15}",106.0,set(),106.0,"{1, 19, 15, 7}",106.0,...,1.0,1.0,1.0,0.013439,0.000402,1,206,35,studentmath (30),0
4,5,106.0,set(),106.0,"{3, 37, 8, 14, 15}",106.0,set(),106.0,"{1, 7, 14, 15, 19}",106.0,...,1.0,1.0,1.0,0.015760,0.000402,1,206,35,studentmath (30),0

In [4]:
greedy_bruteforce_algosdf = pd.DataFrame()
all_bruteforce = pd.DataFrame()

for lx in range(len(graphs)):

    r_edges_random  = graphs[lx]["edges"]
    r_labels_random = graphs[lx]["labels"]
    
    optls = budget_opts(edges=r_edges_random, labels=r_labels_random, budget=5)
    df_optls = pd.DataFrame(optls)
    df_optls["graphidx"] = [lx]*len(df_optls)
    all_bruteforce = pd.concat([all_bruteforce, df_optls], ignore_index=True)


    df_greedy11 = df_greedy1[df_greedy1["graphid"]==lx][['K', 'Sg', 'F(Sg)', 'Sr', 'F(Sr)', '(Sg+ U Sg-)*',
                                                         'F(Sg+ U Sg-)*', '(Sr+ U Sr-)*', 'F(Sr+ U Sr-)*', 'kmax']]

    merged = pd.merge(df_greedy11, df_optls, left_on="K", right_on="b", how="inner").drop(columns=["b"])
    merged["F(Sg)/F(S*)"] = merged["F(Sg)"] / merged["F(S*)"]
    merged["F(Sr)/F(S*)"] = merged["F(Sr)"] / merged["F(S*)"]
    merged["F(Sg+ U Sg-)* / F(S*)"] = merged["F(Sg+ U Sg-)*"] / merged["F(S*)"]
    merged["F(Sr+ U Sr-)* / F(S*)"] = merged["F(Sr+ U Sr-)*"] / merged["F(S*)"]

    summary_dfv = merged[[
        "K", "Sg", "F(Sg)", "Sr", "F(Sr)", "(Sg+ U Sg-)*", "F(Sg+ U Sg-)*",
        "(Sr+ U Sr-)*", "F(Sr+ U Sr-)*", "F(S*)", "S*",
        "F(Sg)/F(S*)", "F(Sr)/F(S*)", "F(Sg+ U Sg-)* / F(S*)", "F(Sr+ U Sr-)* / F(S*)",
        "BFtime", "kmax"
    ]]

    summary_df = summary_dfv.copy()
    summary_df["n"] = [graphs[lx]['n']]*len(summary_df)
    summary_df["m"] = [graphs[lx]['m']]*len(summary_df)
    summary_df["dataset"] = [name+" ("+ str(d) + ")"]*len(summary_df)
    summary_df["graphid"] = [lx]*len(summary_df)

    
    greedy_bruteforce_algosdf = pd.concat([greedy_bruteforce_algosdf, summary_df], ignore_index=True)

## Thresholding

In [5]:
df_greedy1z = pd.read_csv("./sm_results/"+name+"_thresh_summary.csv")
df_greedy1z.head()

,K,F(Sg+ U Sg-)*,(Sg+ U Sg-)*,F(Sr+ U Sr-)*,(Sr+ U Sr-)*,F(Sg),Sg,F(Sr),Sr,F(Sgfull),...,F(Sg)/F(Sr),F(Sg)/F(Sgfull),F(Sr)/F(Srfull),budgetGreedyTime,budgetRdmTime,r,n,m,dataset,graphid
0,1,11.0,{17},11.0,{17},11.0,{0},10.5,{3},11.0,...,1.047619,1.0,0.954545,0.006476,0.000978,4.0,206,9,studentmath (30),0
1,2,11.0,{17},11.0,"{17, 36}",11.0,{0},11.0,"{0, 3}",11.0,...,1.000000,1.0,1.000000,0.011287,0.000574,4.0,206,9,studentmath (30),0
2,3,11.0,{17},11.0,"{17, 10, 36}",11.0,{0},11.0,"{0, 9, 3}",11.0,...,1.000000,1.0,1.000000,0.013919,0.000618,4.0,206,9,studentmath (30),0
3,4,11.0,{17},11.0,"{17, 10, 3, 36}",11.0,{0},11.0,"{0, 9, 3, 36}",11.0,...,1.000000,1.0,1.000000,0.010249,0.000535,4.0,206,9,studentmath (30),0
4,5,11.0,{17},11.0,"{17, 10, 3, 36}",11.0,{0},11.0,"{0, 3, 36, 9, 24}",11.0,...,1.000000,1.0,1.000000,0.008815,0.000403,4.0,206,9,studentmath (30),0

In [6]:
greedy_bruteforce_algosdfz = pd.DataFrame()
all_bruteforcez = pd.DataFrame()

for lz in range(len(graphsz)):

    r_edges_randomz  = graphsz[lz]["edges"]
    r_labels_randomz = graphsz[lz]["labels"]
    
    optlsz = budget_opts(edges=r_edges_randomz, labels=r_labels_randomz, budget=5)
    
    df_optlsz = pd.DataFrame(optlsz)
    df_optlsz["graphidx"] = [lz]*len(df_optlsz)
    all_bruteforcez = pd.concat([all_bruteforcez, df_optlsz], ignore_index=True)


    df_greedy11z = df_greedy1z[df_greedy1z["graphid"]==lz][['K', 'Sg', 'F(Sg)', 'Sr', 'F(Sr)', '(Sg+ U Sg-)*',
                                                         'F(Sg+ U Sg-)*', '(Sr+ U Sr-)*', 'F(Sr+ U Sr-)*', 'r']]

    mergedz = pd.merge(df_greedy11z, df_optlsz, left_on="K", right_on="b", how="inner").drop(columns=["b"])
    mergedz["F(Sg)/F(S*)"] = mergedz["F(Sg)"] / mergedz["F(S*)"]
    mergedz["F(Sr)/F(S*)"] = mergedz["F(Sr)"] / mergedz["F(S*)"]
    mergedz["F(Sg+ U Sg-)* / F(S*)"] = mergedz["F(Sg+ U Sg-)*"] / mergedz["F(S*)"]
    mergedz["F(Sr+ U Sr-)* / F(S*)"] = mergedz["F(Sr+ U Sr-)*"] / mergedz["F(S*)"]

    summary_dfzv = mergedz[[
        "K", "Sg", "F(Sg)", "Sr", "F(Sr)", "(Sg+ U Sg-)*", "F(Sg+ U Sg-)*",
        "(Sr+ U Sr-)*", "F(Sr+ U Sr-)*", "F(S*)", "S*",
        "F(Sg)/F(S*)", "F(Sr)/F(S*)", "F(Sg+ U Sg-)* / F(S*)", "F(Sr+ U Sr-)* / F(S*)",
        "BFtime", "r"
    ]]

    summary_dfz = summary_dfzv.copy()
    summary_dfz["n"] = [graphsz[lz]['n']]*len(summary_dfz)
    summary_dfz["m"] = [graphsz[lz]['m']]*len(summary_dfz)
    summary_dfz["dataset"] = [name+" ("+ str(d) + ")"]*len(summary_dfz)
    summary_dfz["graphid"] = [lz]*len(summary_dfz)

    
    greedy_bruteforce_algosdfz = pd.concat([greedy_bruteforce_algosdfz, summary_dfz], ignore_index=True)

# Save Results

In [7]:
greedy_bruteforce_algosdf.head()

,K,Sg,F(Sg),Sr,F(Sr),(Sg+ U Sg-)*,F(Sg+ U Sg-)*,(Sr+ U Sr-)*,F(Sr+ U Sr-)*,F(S*),...,F(Sg)/F(S*),F(Sr)/F(S*),F(Sg+ U Sg-)* / F(S*),F(Sr+ U Sr-)* / F(S*),BFtime,kmax,n,m,dataset,graphid
0,1,set(),106.0,{7},106.0,set(),106.0,{8},106.0,106.0,...,1.0,1.0,1.0,1.0,0.015637,1,206,35,studentmath (30),0
1,2,set(),106.0,"{1, 7}",106.0,set(),106.0,"{8, 3}",106.0,106.0,...,1.0,1.0,1.0,1.0,0.268944,1,206,35,studentmath (30),0
2,3,set(),106.0,"{1, 19, 7}",106.0,set(),106.0,"{8, 3, 15}",106.0,106.0,...,1.0,1.0,1.0,1.0,3.031840,1,206,35,studentmath (30),0
3,4,set(),106.0,"{1, 19, 15, 7}",106.0,set(),106.0,"{8, 3, 14, 15}",106.0,106.0,...,1.0,1.0,1.0,1.0,24.747001,1,206,35,studentmath (30),0
4,5,set(),106.0,"{1, 7, 14, 15, 19}",106.0,set(),106.0,"{3, 37, 8, 14, 15}",106.0,106.0,...,1.0,1.0,1.0,1.0,148.559032,1,206,35,studentmath (30),0

In [8]:
all_bruteforce.head()

   b  F(S*)  S*     BFtime  graphidx
0  0  106.0  {}   0.000899         0
1  1  106.0  {}   0.015637         0
2  2  106.0  {}   0.268944         0
3  3  106.0  {}   3.031840         0
4  4  106.0  {}  24.747001         0

In [9]:
greedy_bruteforce_algosdfz.head()

,K,Sg,F(Sg),Sr,F(Sr),(Sg+ U Sg-)*,F(Sg+ U Sg-)*,(Sr+ U Sr-)*,F(Sr+ U Sr-)*,F(S*),...,F(Sg)/F(S*),F(Sr)/F(S*),F(Sg+ U Sg-)* / F(S*),F(Sr+ U Sr-)* / F(S*),BFtime,r,n,m,dataset,graphid
0,1,{0},11.0,{3},10.5,{17},11.0,{17},11.0,11.0,...,1.0,0.954545,1.0,1.0,0.003287,4.0,206,9,studentmath (30),0
1,2,{0},11.0,"{0, 3}",11.0,{17},11.0,"{17, 36}",11.0,11.0,...,1.0,1.000000,1.0,1.0,0.017620,4.0,206,9,studentmath (30),0
2,3,{0},11.0,"{0, 9, 3}",11.0,{17},11.0,"{17, 10, 36}",11.0,11.0,...,1.0,1.000000,1.0,1.0,0.047474,4.0,206,9,studentmath (30),0
3,4,{0},11.0,"{0, 9, 3, 36}",11.0,{17},11.0,"{17, 10, 3, 36}",11.0,11.0,...,1.0,1.000000,1.0,1.0,0.088208,4.0,206,9,studentmath (30),0
4,5,{0},11.0,"{0, 3, 36, 9, 24}",11.0,{17},11.0,"{17, 10, 3, 36}",11.0,11.0,...,1.0,1.000000,1.0,1.0,0.124274,4.0,206,9,studentmath (30),0

In [10]:
all_bruteforcez.head()

   b  F(S*)   S*    BFtime  graphidx
0  0   10.5   {}  0.000752         0
1  1   11.0  {0}  0.003287         0
2  2   11.0  {0}  0.017620         0
3  3   11.0  {0}  0.047474         0
4  4   11.0  {0}  0.088208         0

In [11]:
greedy_bruteforce_algosdf.to_csv("./sm_results/"+name+"_knn_greedy_rdm_bruteforce.csv", index=False)
all_bruteforce.to_csv("./sm_results/"+name+"_knn_allbruteforce.csv", index=False)

greedy_bruteforce_algosdfz.to_csv("./sm_results/"+name+"_thresh_greedy_rdm_bruteforce.csv", index=False)
all_bruteforcez.to_csv("./sm_results/"+name+"_thresh_allbruteforce.csv", index=False)